import { ShapeIcon } from './ShapeIcon'
import { Marquee, PIPELINE_ITEMS } from './Marquee'
export function Methodology(){return <main className="fx-page methodology-page"><section className="fx-hero"><h1 className="fx-h1">Discover useful motion.<br/>Keep the evidence.</h1><p className="fx-hero__lede">Aura is a human-guided selection layer for generated humanoid motion. It separates generation, explicit kinematic checks, learned motion priors, human preferences, downstream experiments, and provenance so each claim can be inspected independently.</p></section><Marquee label="Aura / methods + claims" items={PIPELINE_ITEMS}/><section className="fx-section"><h2 className="fx-h2 fx-section__title">Six layers, each claim<br/>inspectable on its own</h2><div className="method-grid">
<article className="method-card"><ShapeIcon kind="pair" /><div className="card-kicker">01 / GENERATION</div><h2>NVIDIA Kimodo supplies candidates.</h2><p>Live mode calls NVIDIA Kimodo as the upstream G1 generation engine and saves every result as robot-native NPZ data. Aura does not claim to have trained Kimodo or to own its generation model. The AIST++ starter motions exist only so visitors can rate motion immediately without waiting for generation.</p></article>
<article className="method-card"><ShapeIcon kind="arch" /><div className="card-kicker">02 / SCREENING</div><h2>Explicit checks stay explicit.</h2><p>Aura computes transparent kinematic measurements such as forward progress, path efficiency, root motion, torso lean and foot-motion proxies. These are filters and diagnostics—not dynamics, collision, balance, safety, or real-robot certification.</p></article>
<article className="method-card"><ShapeIcon kind="grid" /><div className="card-kicker">03 / AURA REWARD MODEL</div><h2>Human choices train the Aura model itself.</h2><p>Aura's primary learned model is a compact temporal Transformer over robot-native G1 trajectories. It learns a scalar reward with Bradley–Terry pairwise loss, so a human choice A &gt; B directly teaches the model to make r(A) &gt; r(B). This is the reward-modeling component used in RLHF systems; it is not full RLHF because Aura does not yet optimize the generator or a robot policy against that reward with reinforcement learning.</p></article>
<article className="method-card"><ShapeIcon kind="bowl" /><div className="card-kicker">04 / AUXILIARY MOTION PRIOR</div><h2>AMP-inspired trajectory learning stays separate.</h2><p>Aura also keeps an AMP-inspired state-transition discriminator as an auxiliary motion-prior signal. Separating the human reward model, motion prior, and explicit constraints makes it possible to inspect what each signal contributes instead of collapsing every judgment into one opaque quality score.</p></article>
<article className="method-card"><ShapeIcon kind="flag" /><div className="card-kicker">05 / DOWNSTREAM TEST</div><h2>Aura versus equal-budget random selection.</h2><p>The offline benchmark freezes the selector, reserves motions the selector has never seen, trains the same lightweight behavior-cloning proxy on Aura-selected and random demonstration sets, and reports negative results unchanged. It is an offline kinematic imitation test, not proof of physical robot task success.</p></article>
<article className="method-card"><ShapeIcon kind="arc" /><div className="card-kicker">06 / SOLANA + NEXT STEP</div><h2>Evidence now; physics later.</h2><p>Aura's curation evidence and payments can be verified on Solana devnet. Full AMP would additionally require a physics simulator and a trainable robot policy. That is the natural next validation layer, but Aura deliberately does not label the current learned prior as physical robot validation.</p></article>
</div></section></main>}
