import { StudyHeader } from './StudyHeader'
export function Methodology(){return <main className="page-shell methodology-page"><StudyHeader/><div className="split-hero methodology-hero"><div><div className="eyebrow">AURA / METHODS + CLAIMS</div><h1>Discover useful motion.<br/><em>Keep the evidence.</em></h1></div><p>Aura is a human-guided selection layer for generated humanoid motion. It separates generation, explicit kinematic checks, learned motion priors, human preferences, downstream experiments, and provenance so each claim can be inspected independently.</p></div><section className="method-grid">
<article className="method-card"><div className="card-kicker">01 / GENERATION</div><h2>Text2Motion Aura supplies candidates.</h2><p>Live mode calls NVIDIA Text2Motion Aura as the local G1 generation engine and saves every result as robot-native NPZ data. Aura does not claim to have trained Text2Motion Aura or to own its generation model. The AIST++ starter motions exist only so visitors can rate motion immediately without waiting for generation.</p></article>
<article className="method-card"><div className="card-kicker">02 / SCREENING</div><h2>Explicit checks stay explicit.</h2><p>Aura computes transparent kinematic measurements such as forward progress, path efficiency, root motion, torso lean and foot-motion proxies. These are filters and diagnostics—not dynamics, collision, balance, safety, or real-robot certification.</p></article>
<article className="method-card"><div className="card-kicker">03 / MOTION PRIOR</div><h2>AMP-inspired, without pretending it is full AMP.</h2><p>Aura learns a small discriminator directly from G1 state-transition windows: root-relative joint poses, joint velocities, root velocity and root height. Human pairwise outcomes provide weak acceptance targets. The resulting score is a learned motion prior—not a physics reward, dynamic-stability score, or full Adversarial Motion Priors policy.</p></article>
<article className="method-card"><div className="card-kicker">04 / HUMAN DISCOVERY</div><h2>Pairwise choices remain the source of preference.</h2><p>Generated-motion choices are persisted in SQLite and train Aura's pairwise selector. The learned motion prior is a separate signal, so Aura can distinguish explicit constraints, trajectory-pattern learning, and direct human preference instead of collapsing them into one opaque quality score.</p></article>
<article className="method-card"><div className="card-kicker">05 / DOWNSTREAM TEST</div><h2>Aura versus equal-budget random selection.</h2><p>The offline benchmark freezes the selector, reserves motions the selector has never seen, trains the same lightweight behavior-cloning proxy on Aura-selected and random demonstration sets, and reports negative results unchanged. It is an offline kinematic imitation test, not proof of physical robot task success.</p></article>
<article className="method-card"><div className="card-kicker">06 / SOLANA + NEXT STEP</div><h2>Evidence now; physics later.</h2><p>Aura's curation evidence and payments can be verified on Solana devnet. Full AMP would additionally require a physics simulator and a trainable robot policy. That is the natural next validation layer, but Aura deliberately does not label the current learned prior as physical robot validation.</p></article>
</section></main>}
